package com.hunterhint.hunterhint.domain.models

enum class Region(val id: Int, val region: String) {
    ALTAI_TERRITORY(22, "Алтайский край"),
    AMUR_REGION(28, "Амурская область"),
    ARKHANGELSK_REGION(29, "Архангельская область"),
    ASTRAKHAN_REGION(30, "Астраханская область"),
    BELGOROD_REGION(31, "Белгородская область"),
    BRYANSK_REGION(32, "Брянская область"),
    VLADIMIR_REGION(33, "Владимирская область"),
    VOLGOGRAD_REGION(34, "Волгоградская область"),
    VOLOGDA_REGION(35, "Вологодская область"),
    VORONEZH_REGION(36, "Воронежская область"),
    MOSCOW(77, "город федерального значения Москва"),
    SAINT_PETERSBURG(78, "город федерального значения Санкт-Петербург"),
    SEVASTOPOL(92, "город федерального значения Севастополь"),
    DONETSK_PEOPLES_REPUBLIC(93, "Донецкая Народная Республика"),
    JEWISH_AUTONOMOUS_REGION(79, "Еврейская автономная область"),
    TRANS_BAIKAL_TERRITORY(75, "Забайкальский край"),
    ZAPOROZHYE_REGION(90, "Запорожская область"),
    IVANOVO_REGION(37, "Ивановская область"),
    OTHER_TERRITORIES(99, "Иные территории,включая город и космодром Байконур"),
    IRKUTSK_REGION(38, "Иркутская область"),
    KABARDINO_BALKARIAN_REPUBLIC(7, "Кабардино-Балкарская Республика"),
    KALININGRAD_REGION(39, "Калининградская область"),
    KALUGA_REGION(40, "Калужская область"),
    KAMCHATKA_REGION(41, "Камчатский край"),
    KARACHAY_CHERKESS_REPUBLIC(9, "Карачаево-Черкесская Республика"),
    KEMEROVO_REGION_KUZBASS(42, "Кемеровская область — Кузбасс"),
    KIROV_REGION(43, "Кировская область"),
    KOSTROMA_REGION(44, "Костромская область"),
    KRASNODARSKIY_KRAY(23, "Краснодарский край"),
    KRASNOYARSK_TERRITORY(24, "Красноярский край"),
    KURGAN_REGION(45, "Курганская область"),
    KURSK_REGION(46, "Курская область"),
    LENINGRAD_REGION(47, "Ленинградская область"),
    LIPETSK_REGION(48, "Липецкая область"),
    LUHANSK_PEOPLES_REPUBLIC(94, "Луганская Народная Республика"),
    MAGADAN_REGION(49, "Магаданская область"),
    MOSCOW_OBLAST(50, "Московская область"),
    MURMANSK_REGION(51, "Мурманская область"),
    NENETS_AUTONOMOUS_OKRUG(83, "Ненецкий автономный округ"),
    NIZHNY_NOVGOROD_REGION(52, "Нижегородская область"),
    NOVGOROD_REGION(53, "Новгородская область"),
    NOVOSIBIRSK_REGION(54, "Новосибирская область"),
    OMSK_REGION(55, "Омская область"),
    ORENBURG_REGION(56, "Оренбургская область"),
    ORYOL_REGION(57, "Орловская область"),
    PENZA_REGION(58, "Пензенская область"),
    PERM_REGION(59, "Пермский край"),
    PRIMORSKY_KRAI(25, "Приморский край"),
    PSKOV_REGION(60, "Псковская область"),
    ADYGEA(1, "Республика Адыгея (Адыгея)"),
    ALTAI_REPUBLIC(4, "Республика Алтай"),
    REPUBLIC_OF_BASHKORTOSTAN(2, "Республика Башкортостан"),
    REPUBLIC_OF_BURYATIA(3, "Республика Бурятия"),
    REPUBLIC_OF_DAGESTAN(5, "Республика Дагестан"),
    REPUBLIC_OF_INGUSHETIA(6, "Республика Ингушетия"),
    REPUBLIC_OF_KALMYKIA(8, "Республика Калмыкия"),
    REPUBLIC_OF_KARELIA(10, "Республика Карелия"),
    KOMI_REPUBLIC(11, "Республика Коми"),
    REPUBLIC_OF_CRIMEA(91, "Республика Крым"),
    REPUBLIC_OF_MARI_EL(12, "Республика Марий Эл"),
    REPUBLIC_OF_MORDOVIA(13, "Республика Мордовия"),
    YAKUTIA(14, "Республика Саха (Якутия)"),
    ALANIA(15, "Республика Северная Осетия — Алания"),
    TATARSTAN(16, "Республика Татарстан (Татарстан)"),
    REPUBLIC_OF_TYVA(17, "Республика Тыва"),
    REPUBLIC_OF_KHAKASSIA(19, "Республика Хакасия"),
    ROSTOV_REGION(61, "Ростовская область"),
    RYAZAN_REGION(62, "Рязанская область"),
    SAMARA_REGION(63, "Самарская область"),
    SARATOV_REGION(64, "Саратовская область"),
    SAKHALIN_REGION(65, "Сахалинская область"),
    SVERDLOVSK_REGION(66, "Свердловская область"),
    SMOLENSK_REGION(67, "Смоленская область"),
    STAVROPOL_TERRITORY(26, "Ставропольский край"),
    TAMBOV_REGION(68, "Тамбовская область"),
    TVER_REGION(69, "Тверская область"),
    TOMSK_REGION(70, "Томская область"),
    TULA_REGION(71, "Тульская область"),
    TYUMEN_REGION(72, "Тюменская область"),
    UDMURT_REPUBLIC(18, "Удмуртская Республика"),
    ULYANOVSK_REGION(73, "Ульяновская область"),
    KHABAROVSK_TERRITORY(27, "Хабаровский край"),
    YUGRA(86, "Ханты-Мансийский автономный округ — Югра"),
    KHERSON_REGION(95, "Херсонская область"),
    CHELYABINSK_REGION(74, "Челябинская область"),
    CHECHEN_REPUBLIC(20, "Чеченская Республика"),
    CHUVASHIA(21, "Чувашская Республика — Чувашия"),
    CHUKOTKA_AUTONOMOUS_OKRUG(87, "Чукотский автономный округ"),
    YAMALO_NENETS_AUTONOMOUS_OKRUG(89, "Ямало-Ненецкий автономный округ"),
    YAROSLAVL_REGION(76, "Ярославская область")
}